# This is where you add environment-specific config that should not be checked into the code repo. This includes sensitive data.

# WORDPRESS_REFETCH_INTERVAL = '60'
# WORDPRESS_SPECIFIC_POSTS = 'hem,omsorg,barn-utbildning,val-av-forskola'
