GATSBY_STORE_NAME = 'example.com/1'

ENABLE_GATSBY_REFRESH_ENDPOINT = 1
WORDPRESS_PAGES_PER_FETCH = 250

[target.local]
  GATSBY_SITE_URL = 'http://localhost:9000'
  GATSBY_WORDPRESS_URL = 'https://cms.example.test'
  NODE_TLS_REJECT_UNAUTHORIZED = 0

[target.prod]
  GATSBY_SITE_URL = 'https://www.example.com'
  GATSBY_WORDPRESS_URL = 'https://cms.example.com'

[target.stage]
  GATSBY_SITE_URL = 'https://www-stage.example.com'
  GATSBY_WORDPRESS_URL = 'https://cms-stage.example.com'
